<script lang="ts">
	export let size = 1;
</script>

<svg
	width={128 * size}
	height={128 * size}
	viewBox="0 0 128 128"
	fill="none"
	xmlns="http://www.w3.org/2000/svg"
>
	<g clip-path="url(#clip0_84_222)">
		<path
			d="M64 50C64 57.732 57.732 64 50 64L32.5 64C26.701 64 22 59.299 22 53.5V53.5C22 47.701 26.701 43 32.5 43V43C38.299 43 43 38.299 43 32.5V32.5C43 26.701 47.701 22 53.5 22V22C59.299 22 64 26.701 64 32.5V50Z"
			stroke="black"
			stroke-width="3.5"
			class="svg-elem-1"
		></path>
		<path
			d="M50 64C57.732 64 64 70.268 64 78V95.5C64 101.299 59.299 106 53.5 106V106C47.701 106 43 101.299 43 95.5V95.5C43 89.701 38.299 85 32.5 85V85C26.701 85 22 80.299 22 74.5V74.5C22 68.701 26.701 64 32.5 64H50Z"
			stroke="black"
			stroke-width="3.5"
			class="svg-elem-2"
		></path>
		<path
			d="M64 50C64 57.732 70.268 64 78 64H95.5C101.299 64 106 59.299 106 53.5V53.5C106 47.701 101.299 43 95.5 43V43C89.701 43 85 38.299 85 32.5V32.5C85 26.701 80.299 22 74.5 22V22C68.701 22 64 26.701 64 32.5V50Z"
			stroke="black"
			stroke-width="3.5"
			class="svg-elem-3"
		></path>
		<path
			d="M78 64C70.268 64 64 70.268 64 78V95.5C64 101.299 68.701 106 74.5 106V106C80.299 106 85 101.299 85 95.5V95.5C85 89.701 89.701 85 95.5 85V85C101.299 85 106 80.299 106 74.5V74.5C106 68.701 101.299 64 95.5 64H78Z"
			stroke="black"
			stroke-width="3.5"
			class="svg-elem-4"
		></path>
		<path
			d="M64 95V99.1726C64 109.606 61.7679 119.979 57.5 129.5V129.5"
			stroke="black"
			stroke-width="3.5"
			class="svg-elem-5"
		></path>
	</g>
	<defs>
		<clipPath id="clip0_84_222">
			<rect width="128" height="128" fill="white" class="svg-elem-6"></rect>
		</clipPath>
	</defs>
</svg>

<style>
	/***************************************************
 * Generated by SVG Artista on 1/4/2025, 4:06:30 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

	@keyframes animate-svg-stroke-1 {
		0% {
			stroke-dashoffset: 141.47279357910156px;
			stroke-dasharray: 141.47279357910156px;
		}

		100% {
			stroke-dashoffset: 0;
			stroke-dasharray: 141.47279357910156px;
		}
	}

	.svg-elem-1 {
		animation:
			animate-svg-stroke-1 1s ease-out 0.5s both,
			animate-svg-fill-1 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s both;
	}

	@keyframes animate-svg-stroke-2 {
		0% {
			stroke-dashoffset: 141.4728240966797px;
			stroke-dasharray: 141.4728240966797px;
		}

		100% {
			stroke-dashoffset: 0;
			stroke-dasharray: 141.4728240966797px;
		}
	}

	.svg-elem-2 {
		animation:
			animate-svg-stroke-2 1s ease-out 0.62s both,
			animate-svg-fill-2 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s both;
	}

	@keyframes animate-svg-stroke-3 {
		0% {
			stroke-dashoffset: 141.4728240966797px;
			stroke-dasharray: 141.4728240966797px;
		}

		100% {
			stroke-dashoffset: 0;
			stroke-dasharray: 141.4728240966797px;
		}
	}

	.svg-elem-3 {
		animation:
			animate-svg-stroke-3 1s ease-out 0.74s both,
			animate-svg-fill-3 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s both;
	}

	@keyframes animate-svg-stroke-4 {
		0% {
			stroke-dashoffset: 141.47283935546875px;
			stroke-dasharray: 141.47283935546875px;
		}

		100% {
			stroke-dashoffset: 0;
			stroke-dasharray: 141.47283935546875px;
		}
	}

	.svg-elem-4 {
		animation:
			animate-svg-stroke-4 1s ease-out 0.86s both,
			animate-svg-fill-4 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s both;
	}

	@keyframes animate-svg-stroke-5 {
		0% {
			stroke-dashoffset: 37.418724060058594px;
			stroke-dasharray: 37.418724060058594px;
		}

		100% {
			stroke-dashoffset: 0;
			stroke-dasharray: 37.418724060058594px;
		}
	}

	.svg-elem-5 {
		animation:
			animate-svg-stroke-5 1s ease-out 0.98s both,
			animate-svg-fill-5 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2000000000000002s both;
	}

	@keyframes animate-svg-stroke-6 {
		0% {
			stroke-dashoffset: 514px;
			stroke-dasharray: 514px;
		}

		100% {
			stroke-dashoffset: 0;
			stroke-dasharray: 514px;
		}
	}

	@keyframes animate-svg-fill-6 {
		0% {
			fill: transparent;
		}

		100% {
			fill: rgb(255, 255, 255);
		}
	}

	.svg-elem-6 {
		animation:
			animate-svg-stroke-6 1s ease-out 1.1s both,
			animate-svg-fill-6 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3s both;
	}
</style>
